import sys
import os
import re

with open('ai_agent.py', 'r', encoding='utf-8') as f:
    content = f.read()

# We need to replace everything from "def process_pi_bypass(text, sender, p_id):"
# up to "logging.error(f"Error in PI Bypass: {e}")"

pattern = re.compile(r"def process_pi_bypass\(text, sender, p_id\):.*?logging\.error\(f\"Error in PI Bypass: \{e\}\"\)", re.DOTALL)

new_str = """def process_pi_bypass(text, sender, p_id):
                                        try:
                                            # Strip the 'pi:' prefix for processing
                                            clean_text = re.sub(r'(?i)^pi:\s*', '', text).strip()
                                            actor = {"name": "Admin Manager", "phone": admin_phone, "username": "ahmady", "roles": ["admin"]}
                                            
                                            # Agentic OS Bypass: Directly consult PI as the orchestrator
                                            delegation_payload = {
                                                "delegation_allowed": True,
                                                "should_delegate": True,
                                                "intent": "agentic_orchestrator",
                                                "case_snapshot": {
                                                    "user_request": clean_text
                                                },
                                                "delegation_contract": {
                                                    "type": "full_orchestration",
                                                    "rules": "Analyze user request and select appropriate schemas to execute."
                                                }
                                            }
                                            
                                            pi_result = self._run_pi_real_analysis(delegation_payload, actor=actor)
                                            
                                            # Parse PI Result
                                            structured_result = pi_result.get("structured_result") or {}
                                            if not structured_result and pi_result.get("raw_output"):
                                                try:
                                                    import json
                                                    parsed = json.loads(self._extract_json_like_text(pi_result.get("raw_output")))
                                                    structured_result = self._normalize_pi_structured_result(parsed, pi_result.get("raw_output"), delegation_payload)
                                                except Exception:
                                                    pass

                                            # Save any Manifest generated by PI
                                            action_manifest = structured_result.get("action_manifest")
                                            if action_manifest:
                                                manifest_dict = {}
                                                if isinstance(action_manifest, dict):
                                                    if "actions" in action_manifest:
                                                        manifest_dict = action_manifest
                                                    else:
                                                        manifest_dict = {"intent": "agentic_orchestrator", "actions": [action_manifest]}
                                                elif isinstance(action_manifest, list):
                                                    manifest_dict = {"intent": "agentic_orchestrator", "actions": action_manifest}
                                                
                                                if manifest_dict and manifest_dict.get("actions"):
                                                    try:
                                                        self._write_pi_manifest_to_outbox(actor, manifest_dict)
                                                    except Exception as e:
                                                        logging.error(f"Failed to write PI Agentic manifest: {e}")

                                            reply_text = structured_result.get("internal_reply") or structured_result.get("recommended_internal_reply") or "تم استلام الطلب ومعالجته (Agentic OS)."
                                            
                                            self.send_whatsapp_message(
                                                str(sender).replace("+", ""),
                                                text=reply_text,      
                                                location="Unknown",   
                                                receiving_phone_id=p_id if p_id else None
                                            )
                                        except Exception as e:
                                            logging.error(f"Error in PI Agentic Bypass: {e}")"""

if pattern.search(content):
    content = pattern.sub(new_str, content)
    with open('ai_agent.py', 'w', encoding='utf-8') as f:
        f.write(content)
    print("Bypass updated successfully.")
else:
    print("pattern not found!")
